#!/usr/bin/perl
use v5.10;
use Storable;
use Tokenizer;
use Postings;
use Term::ANSIColor qw(:constants);
use List::MoreUtils qw(any uniq);
use Encode;
use Morfologik;
use warnings;
use strict;
sub debug {
    #say "# ",@_;
}
debug "creating postings...";
my $postings = PostingsPtr::create("index/postings_full");
debug "got here";

binmode *STDOUT, ':encoding(UTF-8)';
binmode *STDIN,  ':encoding(UTF-8)';

debug "loading tokIDs...";
my $h = retrieve('index/tokIDs');
debug "loading morfologik...";
Morfologik::load('m1');
debug "enter query";

sub search {
    my $tokID  = shift;
#    my $tokID = $h->{$word};
#    say "tokID $word = $tokID";
    if ($tokID != -1) {
        #say "searching for tokID: $tokID";
        $postings->search($tokID);
    } else {
        $postings->empty();
    }
}

sub to_id {
    my $tok = shift;
    $h->{$tok} // -1;
}
sub possible {
    my $tok = shift;
    #debug "all possibilites for $tok:",join(',',@{Morfologik::get(lc $tok)});
    map {to_id($_)} @{Morfologik::get(lc $tok)};
}

sub or_query {
    my ($q) = @_;
    my @or = map {possible($_)} split( '\|', $q );
    my $result = search( shift @or );
    for my $w (@or) {
        $result = $result->or( search($w) );
    }
    $result;
}

open (my $titles,'index/titles');
binmode $titles,  ':encoding(UTF-8)';

my @titles = <$titles>;
sub title {
    my $docID = shift;
    my $title = $titles[$docID];
    chomp($title);
    $title;
}

sub report {
    my ($query,$result) = @_;
    my @documents = $result->flatten;
    say "QUERY: $query TOTAL: ", $#documents + 1;
    for my $docID (@documents[0..4]) {
        say title($docID);
    }
}

while ( my $q = <> ) {
    chomp($q);
    my $q = lc $q;
    if ( $q =~ /"(.*)"/ ) {
        my @parts = split(' ',$1);
        my $result = search( shift @parts );
        for my $w (@parts) {
            $result = $postings->phrase($result, search($w) );
        }
        report($q,$result);
    }
    else {
        my @ands = split( ' ', $q );
        my $result = or_query( shift @ands );
        for my $and (@ands) {
            $result = $result->and( or_query($and) );
        }
        report($q,$result);
    }

}
