#!/usr/bin/perl
use strict;
use warnings;
use v5.10;
use utf8::all;
do 'stem.pl';
sub prefix {
    my $word = shift;;
    $word =~ s/^(nie|naj)+//;
    $word;
}
while (my $input = <>) {
    chomp($input);
    $input = prefix($input);
    $input = suffix($input);
    say $input;
}
