#!/usr/bin/perl
use v5.10;
use strict;
use warnings;

use Encode;
use List::MoreUtils qw(any);
use Term::ANSIColor qw(:constants);
use Term::ProgressBar;
use Tokenizer;
use Morfologik;
use Storable;

mkdir('index');
#system('ln -s /home/pawel/wyszukiwarka/raw index/raw');
#say "wc -l $ARGV[0]";
my $max = 15255080;#`wc -l $ARGV[0]`;

say "Loading morfologik...";
Morfologik::load();
say "Loaded morfologik.";

my $progress = Term::ProgressBar->new({name => 'Powers', count => $max, remove => 1, ETA=> "linear"});
open(my $file,$ARGV[0]);
open(my $titles,">index/titles");
binmode $titles, ':encoding(UTF-8)';
binmode $file, ':encoding(UTF-8)';
binmode *STDOUT, ':encoding(UTF-8)';

use constant maxTokens => 5_000_000;
my $part = 0;
my $tokens = 0;

my %h;
my $tokID = 0;

sub to_id {
    my $tok = shift;
    unless ($h{$tok}) {
        $h{$tok} = $tokID++; 
    }
    $h{$tok};
}

sub possible {
    my $tok = shift;
    map {to_id($_)} @{Morfologik::get(lc $tok)};
}
sub read_file {
    my @titles;
    my $next_update = 0;
    my $docID = -1;
    my $pos = 0;

    # hopefully this will be enough
    my $tokenizer = TokenizerPtr::create(2*maxTokens);

    while (my $line = <$file>) {
        $next_update = $progress->update($.) if $. >= $next_update;
        if ($line =~ /^##TITLE## (.*)\n/) {
            say $titles $1;
            if ($tokenizer->bufTop > maxTokens) {
                $tokenizer->sort;
                $tokenizer->write("index/postings$part");
                $tokenizer = TokenizerPtr::create(2*maxTokens);
                $part++;
            }
            $docID++;
            $line = $1;
        }
        my @tokens = split(/\W+/,$line);
        for (@tokens) {
            next unless $_;
            $tokenizer->add($_,$docID,$pos) for possible($_);
            $pos++;
        }

    }
    $progress->update($max);
    say "updating...";
    say "writing...";
    say "storing tokens...";

    $tokenizer->sort;
    $tokenizer->write("index/postings$part");
    $part++;

    say "writing tokIDs...";

    store \%h,'index/tokIDs';


    say "writing titles...";
    

}

read_file;
